### ISSUE TITLE
Esploit settings "site not working" 

### ISSUE THREAD

**Issue by PzmuV1517** [whid-injector/WHID#97]
I made changes in configurations then i pressed apply setting and then chrome said "site not working. 192.168.1.1 didn't send any data"
What should I do.

**Comment by whid-injector** [comment]
I won't spend time explaining in depth how to report issues, since I am pretty sure you have done it tons of times. The main idea can be summed up in the following points:

Expected Behavior
Unexpected Behavior
which OS you using?
Which Arduino IDE version you using?
Is the target computer an Apple Product?
Is the target USB port an USB3.0?
Eventual Explanation Notes, Screenshots, Videos, etc.
